import { FormEvent, ReactNode, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { api, formatDate, jsonBody } from './api'
import { useAuth } from './AuthContext'
import { MapView } from './MapView'
import { ImportTab, SourcesTab } from './SourceCatalog'
import { HelpTooltip, LabelHelp } from './HelpTooltip'
import type { ImportArea } from './SourceCatalog'
import type { AnalysisDefinition, AnalysisResult, AnalysisRun, EventLog, Layer, Project, Role, User } from './types'
const TABS = ['Mapa','Dane','Import','Analizy','Wyniki','Logi','Źródła danych'] as const
const TAB_HINTS: Record<typeof TABS[number],string> = {
  Mapa: 'Włączaj warstwy, oglądaj geometrie i klikaj obiekty, aby zobaczyć ich atrybuty.',
  Dane: 'Lista warstw projektu, ich typów, liczebności i metadanych reprodukowalności.',
  Import: 'Prowadzony import z katalogu zweryfikowanych źródeł albo z pobranego pliku.',
  Analizy: 'Konfiguracja i uruchamianie analiz relacji geometrycznych między warstwami.',
  Wyniki: 'Filtrowanie, przeglądanie i eksport wyników analiz do CSV lub GeoJSON.',
  Logi: 'Chronologiczny zapis importów, analiz i zmian wykonanych w projekcie.',
  'Źródła danych': 'Katalog wiedzy o dostępności, rocznikach, ograniczeniach i sposobach pozyskania danych.',
}

function ErrorMessage({ error }: { error: unknown }) { return error instanceof Error ? <p className="alert error">{error.message}</p> : null }
function Status({ value }: { value: string }) { return <span className={`status status-${value.toLowerCase()}`}>{value}</span> }
function Empty({ children }: { children: ReactNode }) { return <div className="empty">{children}</div> }

function LoginPage() {
  const { user, login } = useAuth()
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  if (user) return <Navigate to="/projects" replace />
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError('')
    try { await login(email, password); navigate('/projects') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Nie udało się zalogować') }
  }
  return <main className="login-page">
    <section className="login-copy"><div className="brand-mark">GH</div><p className="eyebrow">ŚRODOWISKO BADAWCZE</p><h1>GeoHarmonizer</h1><p>Analiza relacji geometrycznych między EGiB, LPIS i innymi warstwami wektorowymi.</p><div className="research-note">Wyniki wskazują kandydatów do dalszej weryfikacji. Nie stanowią rozstrzygnięcia prawnego ani automatycznej korekty danych.</div></section>
    <form className="login-card" onSubmit={submit}><p className="eyebrow">DOSTĘP DO APLIKACJI</p><h2>Zaloguj się</h2><p className="muted">Użyj konta utworzonego przez administratora.</p><label>E-mail<input type="email" value={email} onChange={event => setEmail(event.target.value)} required autoFocus /></label><label>Hasło<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label>{error && <p className="alert error">{error}</p>}<button className="primary" type="submit">Zaloguj się</button></form>
  </main>
}

function Shell({ children }: { children: ReactNode }) {
  const { user, loading, logout } = useAuth()
  if (loading) return <div className="loading">Ładowanie aplikacji…</div>
  if (!user) return <Navigate to="/login" replace />
  return <div className="app-shell"><header className="topbar"><Link to="/projects" className="brand"><span className="brand-mark small">GH</span><span>GeoHarmonizer<small>środowisko badawcze</small></span></Link><nav><Link to="/projects">Projekty</Link>{user.role === 'ADMIN' && <Link to="/users">Użytkownicy</Link>}</nav><div className="account"><span><strong>{user.email}</strong><small>{user.role}</small></span><button className="secondary" onClick={() => logout()}>Wyloguj</button></div></header>{children}</div>
}

function ProjectsPage() {
  const { user } = useAuth(); const queryClient = useQueryClient()
  const projects = useQuery({ queryKey: ['projects'], queryFn: () => api<Project[]>('/api/projects') })
  const [showForm, setShowForm] = useState(false)
  const create = useMutation({ mutationFn: (data: Record<string,string>) => api<Project>('/api/projects', { method:'POST', ...jsonBody(data) }), onSuccess: () => { queryClient.invalidateQueries({queryKey:['projects']}); setShowForm(false) } })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: String(form.get('name')), description: String(form.get('description') ?? '') }) }
  return <Shell><main className="page"><div className="page-heading"><div><p className="eyebrow">WSPÓLNA PRZESTRZEŃ</p><h1>Projekty badawcze</h1><p>Zestawiaj źródła, uruchamiaj analizy i dokumentuj wyniki.</p></div>{user?.role !== 'VIEWER' && <button className="primary" onClick={() => setShowForm(!showForm)}>+ Nowy projekt</button>}</div>
    {showForm && <form className="panel form-grid" onSubmit={submit}><label className="span-2">Nazwa projektu<input name="name" required /></label><label className="span-2">Opis<textarea name="description" rows={2}/></label><div className="span-2 actions"><button className="secondary" type="button" onClick={() => setShowForm(false)}>Anuluj</button><button className="primary">Utwórz projekt</button></div><ErrorMessage error={create.error}/></form>}
    {projects.isLoading ? <div className="loading">Ładowanie projektów…</div> : projects.data?.length ? <div className="project-grid">{projects.data.map(project => <Link className="project-card" to={`/projects/${project.id}`} key={project.id}><div className="project-card-top"><span className="project-icon">⌖</span><span className="arrow">→</span></div><h2>{project.name}</h2><p>{project.description || 'Bez opisu'}</p><div className="stats"><span><strong>{project.layer_count}</strong> warstw</span><span><strong>{project.analysis_count}</strong> analiz</span></div><small>Aktualizacja: {formatDate(project.updated_at)}</small></Link>)}</div> : <Empty>Nie ma jeszcze projektów. Utwórz pierwszy projekt badawczy.</Empty>}<ErrorMessage error={projects.error}/></main></Shell>
}

function DataTab({ projectId, layers }: {projectId:string;layers:Layer[]}) {
  const [metadataId, setMetadataId] = useState('')
  const metadata = useQuery({ queryKey:['metadata',metadataId], queryFn:()=>api<any>(`/api/projects/${projectId}/layers/${metadataId}/metadata`), enabled:!!metadataId })
  if (!layers.length) return <Empty>Brak warstw. Zaimportuj GeoJSON, GPKG, SHP ZIP, GML lub WFS.</Empty>
  return <><div className="table-wrap"><table><thead><tr><th>Nazwa</th><th>Typ</th><th>Geometria</th><th>Obiekty</th><th>CRS</th><th>Źródło</th><th>Import</th><th/></tr></thead><tbody>{layers.map(layer=><tr key={layer.id}><td><strong>{layer.name}</strong></td><td><code>{layer.layer_type}</code></td><td>{layer.geometry_type}</td><td>{layer.feature_count}</td><td>EPSG:{layer.srid}</td><td>{layer.source_name || '—'}</td><td>{formatDate(layer.created_at)}</td><td><button className="link-button" title="Pokaż pełne metadane importu, CRS, zakres i informacje o źródle" onClick={()=>setMetadataId(layer.id)}>Metadane</button></td></tr>)}</tbody></table></div>{metadataId && <div className="modal-backdrop" onClick={()=>setMetadataId('')}><section className="modal" onClick={event=>event.stopPropagation()}><button className="icon-button" onClick={()=>setMetadataId('')}>×</button><h2>Metadane warstwy <HelpTooltip text="Metadane pozwalają odtworzyć pochodzenie i przekształcenia danych użytych w badaniu."/></h2>{metadata.isLoading?<p>Ładowanie…</p>:<pre>{JSON.stringify(metadata.data,null,2)}</pre>}</section></div>}</>
}

function AnalysisTab({projectId,layers,definitions}:{projectId:string;layers:Layer[];definitions:AnalysisDefinition[]}) {
  const {user}=useAuth();const queryClient=useQueryClient();const [key,setKey]=useState('');const selectedKey=key||definitions[0]?.key||'';const definition=definitions.find(item=>item.key===selectedKey);const [message,setMessage]=useState('')
  const run=useMutation({mutationFn:(body:any)=>api<AnalysisRun>(`/api/projects/${projectId}/analysis-runs`,{method:'POST',...jsonBody(body)}),onSuccess:result=>{setMessage(`Analiza zakończona: ${result.result_summary_json.result_count??0} wyników.`);queryClient.invalidateQueries({queryKey:['runs',projectId]})}})
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!definition)return;const f=new FormData(event.currentTarget);const inputs=Object.fromEntries(Object.keys(definition.input_requirements).map(name=>[name,f.get(name)]));const parameters=Object.fromEntries(Object.entries(definition.parameters_schema).map(([name,defaultValue])=>[name,typeof defaultValue==='boolean'?f.get(name)==='on':Number(f.get(name))]));run.mutate({analysis_key:selectedKey,name:f.get('name')||definition.name,inputs,parameters})}
  return <div className="split"><section><p className="eyebrow">KATALOG ANALIZ</p>{definitions.map(item=><button className={`analysis-card ${selectedKey===item.key?'selected':''}`} title={item.description} onClick={()=>setKey(item.key)} key={item.key}><span>⌁</span><div><strong>{item.name}</strong><small>{item.description}</small></div></button>)}</section><section className="panel"><h2>Parametry analizy <HelpTooltip text="Warstwy wejściowe muszą odpowiadać wymaganym profilom. Parametry liczbowe określają tolerancje przestrzenne analizy."/></h2>{!definition?<Empty>Brak definicji analiz. Wykonaj migrację.</Empty>:<form className="stack" onSubmit={submit}><label><LabelHelp label="Nazwa uruchomienia" text="Czytelna nazwa ułatwia późniejsze porównanie wielu wariantów tej samej analizy."/><input name="name" placeholder={definition.name}/></label>{Object.entries(definition.input_requirements).map(([name,type])=><label key={name}><LabelHelp label={`${name} (${type})`} text="Wybierz warstwę projektu pełniącą wskazaną rolę wejściową w analizie."/><select name={name} required><option value="">Wybierz warstwę…</option>{layers.map(layer=><option key={layer.id} value={layer.id}>{layer.name} · {layer.geometry_type}</option>)}</select></label>)}{Object.entries(definition.parameters_schema).map(([name,value])=>typeof value==='boolean'?<label className="checkbox" key={name}><input name={name} type="checkbox" defaultChecked={value}/>{name}<HelpTooltip text="Włącza lub wyłącza tę opcję dla bieżącego uruchomienia analizy."/></label>:<label key={name}><LabelHelp label={name} text="Wartość tolerancji używana przez algorytm. Jednostką jest metr, o ile opis analizy nie stanowi inaczej."/><input name={name} type="number" step="any" min="0" defaultValue={value}/></label>)}{user?.role!=='VIEWER'&&<button className="primary" disabled={run.isPending}>{run.isPending?'Analiza trwa…':'Uruchom analizę'}</button>}</form>}<ErrorMessage error={run.error}/>{message&&<p className="alert success">{message}</p>}</section></div>
}

function ResultsTab({projectId,runs}:{projectId:string;runs:AnalysisRun[]}) {
  const [runId,setRunId]=useState('');const selectedRunId=runId||runs[0]?.id||'';const [type,setType]=useState('');const [severity,setSeverity]=useState('')
  const results=useQuery({queryKey:['results',projectId,selectedRunId],queryFn:()=>api<AnalysisResult[]>(`/api/projects/${projectId}/analysis-runs/${selectedRunId}/results?limit=5000`),enabled:!!selectedRunId})
  const filtered=useMemo(()=>results.data?.filter(item=>(!type||item.result_type===type)&&(!severity||item.severity===severity))??[],[results.data,type,severity])
  const types=Array.from(new Set(results.data?.map(item=>item.result_type)??[]))
  if(!runs.length)return <Empty>Nie uruchomiono jeszcze żadnej analizy.</Empty>
  return <><div className="filters"><label><LabelHelp label="Uruchomienie" text="Wybierz konkretny przebieg analizy; każde uruchomienie zachowuje własne parametry i wyniki."/><select value={selectedRunId} onChange={event=>setRunId(event.target.value)}>{runs.map(run=><option key={run.id} value={run.id}>{run.name} · {run.status}</option>)}</select></label><label><LabelHelp label="Typ" text="Ogranicza tabelę do jednego rodzaju wykrytej relacji lub niezgodności."/><select value={type} onChange={event=>setType(event.target.value)}><option value="">Wszystkie</option>{types.map(value=><option key={value}>{value}</option>)}</select></label><label><LabelHelp label="Priorytet" text="Priorytet wspiera przegląd wyników, ale nie jest rozstrzygnięciem prawnym ani oceną jakości źródła."/><select value={severity} onChange={event=>setSeverity(event.target.value)}><option value="">Wszystkie</option>{['INFO','LOW','MEDIUM','HIGH'].map(value=><option key={value}>{value}</option>)}</select></label><div className="export-actions"><a className="secondary button-link" title="Pobierz geometrię i atrybuty wyników" href={`/api/projects/${projectId}/analysis-runs/${selectedRunId}/results.geojson`}>Eksport GeoJSON</a><a className="secondary button-link" title="Pobierz tabelę wyników bez geometrii" href={`/api/projects/${projectId}/analysis-runs/${selectedRunId}/results.csv`}>Eksport CSV</a></div></div><div className="table-wrap"><table><thead><tr><th>Priorytet</th><th>Typ</th><th>Opis</th><th>Rekomendacja</th><th>Metryki</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><Status value={item.severity}/></td><td><code>{item.result_type}</code></td><td><strong>{item.label}</strong><small>{item.description}</small></td><td>{item.recommendation}</td><td><details><summary>Pokaż</summary><pre>{JSON.stringify(item.metrics_json,null,2)}</pre></details></td></tr>)}</tbody></table></div></>
}

function LogsTab({projectId}:{projectId:string}) { const logs=useQuery({queryKey:['logs',projectId],queryFn:()=>api<EventLog[]>(`/api/projects/${projectId}/logs`)});return logs.data?.length?<div className="timeline logs">{logs.data.map(item=><article key={item.id}><Status value={item.level}/><strong>{item.message}</strong><small>{formatDate(item.created_at)} · {item.entity_type}</small>{item.details_json&&<details><summary>Szczegóły</summary><pre>{JSON.stringify(item.details_json,null,2)}</pre></details>}</article>)}</div>:<Empty>Brak zdarzeń w projekcie.</Empty> }
function ProjectPage(){const {projectId=''}=useParams();const navigate=useNavigate();const {user}=useAuth();const queryClient=useQueryClient();const [tab,setTab]=useState<typeof TABS[number]>('Mapa');const [importArea,setImportArea]=useState<ImportArea|null>(null);const [selectingImportArea,setSelectingImportArea]=useState(false);const project=useQuery({queryKey:['project',projectId],queryFn:()=>api<Project>(`/api/projects/${projectId}`)});const layers=useQuery({queryKey:['layers',projectId],queryFn:()=>api<Layer[]>(`/api/projects/${projectId}/layers`)});const definitions=useQuery({queryKey:['definitions'],queryFn:()=>api<AnalysisDefinition[]>('/api/analysis-definitions')});const runs=useQuery({queryKey:['runs',projectId],queryFn:()=>api<AnalysisRun[]>(`/api/projects/${projectId}/analysis-runs`)});const remove=useMutation({mutationFn:()=>api<void>(`/api/projects/${projectId}`,{method:'DELETE'}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:['projects']});navigate('/projects')}})
  if(project.isLoading)return <Shell><div className="loading">Ładowanie projektu…</div></Shell>
  if(project.error)return <Shell><main className="page"><ErrorMessage error={project.error}/></main></Shell>
  const startAreaSelection=()=>{setSelectingImportArea(true);setTab('Mapa')};const finishAreaSelection=(area:ImportArea)=>{setImportArea(area);setSelectingImportArea(false);setTab('Import')};const cancelAreaSelection=()=>{setSelectingImportArea(false);setTab('Import')}
  return <Shell><main className={`project-page ${tab==='Mapa'?'map-page':''}`}><div className="project-header"><div><Link to="/projects" className="back">← Projekty</Link><div className="project-title-line"><h1>{project.data?.name}</h1>{project.data?.description&&<p>{project.data.description}</p>}</div></div>{user?.role!=='VIEWER'&&<button className="danger" onClick={()=>{if(confirm('Usunąć projekt wraz ze wszystkimi danymi?'))remove.mutate()}}>Usuń projekt</button>}</div><nav className="tabs">{TABS.map(name=><button className={tab===name?'active':''} title={TAB_HINTS[name]} onClick={()=>setTab(name)} key={name}>{name}</button>)}</nav><section className={`tab-content ${tab==='Mapa'?'map-content':''}`}>{tab==='Mapa'&&<MapView projectId={projectId} layers={layers.data??[]} runs={runs.data??[]} selectingImportArea={selectingImportArea} onImportAreaSelected={finishAreaSelection} onCancelImportArea={cancelAreaSelection}/>} {tab==='Dane'&&<DataTab projectId={projectId} layers={layers.data??[]}/>} {tab==='Import'&&<ImportTab projectId={projectId} area={importArea} onAreaChange={setImportArea} onSelectOnMap={startAreaSelection}/>} {tab==='Analizy'&&<AnalysisTab projectId={projectId} layers={layers.data??[]} definitions={definitions.data??[]}/>} {tab==='Wyniki'&&<ResultsTab projectId={projectId} runs={runs.data??[]}/>} {tab==='Logi'&&<LogsTab projectId={projectId}/>} {tab==='Źródła danych'&&<SourcesTab/>}</section></main></Shell>}

function UsersPage(){const {user}=useAuth();const queryClient=useQueryClient();const users=useQuery({queryKey:['users'],queryFn:()=>api<User[]>('/api/users'),enabled:user?.role==='ADMIN'});const create=useMutation({mutationFn:(body:any)=>api<User>('/api/users',{method:'POST',...jsonBody(body)}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['users']})});const toggle=useMutation({mutationFn:({id,active}:{id:string;active:boolean})=>api<User>(`/api/users/${id}/${active?'deactivate':'activate'}`,{method:'POST'}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['users']})});const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);create.mutate({email:f.get('email'),password:f.get('password'),role:f.get('role') as Role});event.currentTarget.reset()};if(user?.role!=='ADMIN')return <Navigate to="/projects" replace/>;return <Shell><main className="page"><div className="page-heading"><div><p className="eyebrow">ADMINISTRACJA</p><h1>Użytkownicy</h1><p>Konta mają dostęp do wspólnej przestrzeni projektowej.</p></div></div><form className="panel inline-form" onSubmit={submit}><label>E-mail<input name="email" type="email" required/></label><label>Hasło początkowe<input name="password" type="password" minLength={10} required/></label><label>Rola<select name="role"><option>USER</option><option>VIEWER</option><option>ADMIN</option></select></label><button className="primary">Utwórz konto</button></form><ErrorMessage error={create.error}/><div className="table-wrap"><table><thead><tr><th>E-mail</th><th>Rola</th><th>Status</th><th>Utworzono</th><th/></tr></thead><tbody>{users.data?.map(item=><tr key={item.id}><td><strong>{item.email}</strong></td><td>{item.role}</td><td><Status value={item.is_active?'ACTIVE':'INACTIVE'}/></td><td>{formatDate(item.created_at)}</td><td><button className="link-button" disabled={item.id===user.id} onClick={()=>toggle.mutate({id:item.id,active:item.is_active})}>{item.is_active?'Dezaktywuj':'Aktywuj'}</button></td></tr>)}</tbody></table></div></main></Shell>}

export function App(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/projects" element={<ProjectsPage/>}/><Route path="/projects/:projectId" element={<ProjectPage/>}/><Route path="/users" element={<UsersPage/>}/><Route path="*" element={<Navigate to="/projects" replace/>}/></Routes>}
